# Site settings
title: Costin Galan
description: A presentation 
baseurl: ""
url: "http://cogala.eu"

username: costingalan
user_description: 
user_title: Cloud Engineer
email: costin@cogala.eu
github_username:  costingalan

google-analytics:
  id: "UA-91241617-1"

exclude: ['package.json', 'src' , 'node_modules']
